### ISSUE TITLE
[ issue ] - ReferenceError: globalThis is not defined

### ISSUE THREAD

**Issue by aekiratli** [feross/queue-microtask#16]
node version: 11
os: Linux 4e384c3fd858 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
yarn version: v1.13.0

```
[12:29:25]Step 5/9: Gulp (Command Line) (3s)
[12:29:25][Step 5/9] Content of /opt/buildagent/temp/agentTmp/custom_script6562944589522696064 file: yarn build
[12:29:25][Step 5/9] Starting: /opt/buildagent/temp/agentTmp/custom_script6562944589522696064
[12:29:25][Step 5/9] in directory: /opt/buildagent/work/f109404eb773f13c
[12:29:25][Step 5/9] yarn run v1.13.0
[12:29:25][Step 5/9] warning ../../../../package.json: No license field
[12:29:25][Step 5/9] $ NODE_ENV=production node_modules/.bin/gulp
[12:29:28][Step 5/9] (node:2710) ExperimentalWarning: queueMicrotask() is experimental.
[12:29:28][Step 5/9] ReferenceError: globalThis is not defined
[12:29:28][Step 5/9]     at Object.<anonymous> (/opt/buildagent/work/f109404eb773f13c/node_modules/queue-microtask/index.js:5:25)
[12:29:28][Step 5/9]     at Module._compile (internal/modules/cjs/loader.js:816:30)
[12:29:28][Step 5/9]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
[12:29:28][Step 5/9]     at Module.load (internal/modules/cjs/loader.js:685:32)
[12:29:28][Step 5/9]     at Function.Module._load (internal/modules/cjs/loader.js:620:12)
[12:29:28][Step 5/9]     at Module.require (internal/modules/cjs/loader.js:723:19)
[12:29:28][Step 5/9]     at require (internal/modules/cjs/helpers.js:14:16)
[12:29:28][Step 5/9]     at Object.<anonymous> (/opt/buildagent/work/f109404eb773f13c/node_modules/run-parallel/index.js:4:24)
[12:29:28][Step 5/9]     at Module._compile (internal/modules/cjs/loader.js:816:30)
[12:29:28][Step 5/9]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
[12:29:28][Step 5/9]     at Module.load (internal/modules/cjs/loader.js:685:32)
[12:29:28][Step 5/9]     at Function.Module._load (internal/modules/cjs/loader.js:620:12)
[12:29:28][Step 5/9]     at Module.require (internal/modules/cjs/loader.js:723:19)
[12:29:28][Step 5/9]     at require (internal/modules/cjs/helpers.js:14:16)
[12:29:28][Step 5/9]     at Object.<anonymous> (/opt/buildagent/work/f109404eb773f13c/node_modules/@nodelib/fs.scandir/out/providers/async.js:5:13)
[12:29:28][Step 5/9]     at Module._compile (internal/modules/cjs/loader.js:816:30)
[12:29:28][Step 5/9] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[12:29:28][Step 5/9] error Command failed with exit code 1.
[12:29:28][Step 5/9] Process exited with code 1
[12:29:28][Step 5/9] Process exited with code 1 (Step: Gulp (Command Line))
[12:29:28][Step 5/9] Step Gulp (Command Line) failed
```

```
ReferenceError: globalThis is not defined
```

I'm getting this error

**Comment by aekiratli** [comment]
okay just saw this
https://github.com/feross/queue-microtask/issues/13
